name: Test

on:
  push:

jobs:
  test-solo-lowercase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: solo
        uses: romanlamsal/dotenv-concat@main
        with:
          paths: ./test/.env.solo
      - run: echo ${{ steps.solo.outputs.foo }}
      - run: echo ${{ steps.solo.outputs.FOO }}
  test-multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: multi
        uses: romanlamsal/dotenv-concat@main
        with:
          paths: >-
            test/.env.multi1,
            test/.env.multi2
      - run: |
          echo ${{ steps.multi.outputs.foo }}
          echo ${{ steps.multi.outputs.bar }}
          echo ${{ steps.multi.outputs.baz }}
